# based on https://gist.github.com/learnopengles/60c945b92fbe60a0fecaa0143c35c4a for testing in simulator
name: x86_64-apple-ios

on: pull_request

env:
  TOOLCHAIN: nightly
  CARGO_TERM_COLOR: always
  DYLD_ROOT_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/

jobs:
  integration_tests:
    # rust cross-compilation
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-ios
          default: true
      - name: Set up Elixir
        run: brew install elixir
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ github.workflow }}-${{ github.job }}-toolchain-${{ env.TOOLCHAIN }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: tests/support/test_server/deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-2-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: tests/support/test_server/_build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-2-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-
      - name: Build phoenix_channels_client
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: Install hex
        run: mix local.hex --force
      - name: Install rebar3
        run: mix local.rebar --force
      - name: Install test server dependencies
        working-directory: ./tests/support/test_server
        run: mix deps.get
      - name: Build test server
        working-directory: ./tests/support/test_server
        run: mix compile
      - name: Set linker
        run: echo "CARGO_TARGET_X86_64_APPLE_IOS_LINKER=$PWD/tests/support/linker_shim.sh" >> $GITHUB_ENV
      - name: Build integration tests
        run: cargo test --no-run --target=x86_64-apple-ios
      - name: Copy integration tests to app bundle
        run: cp `find target/x86_64-apple-ios/debug/deps/ -perm +111 -type f -name "integration_test-*"` tests/support/app/integration_test
      - name: Start Simulator
        uses: futureware-tech/simulator-action@v2
        with:
          os: 'iOS'
      - name: Install integration tests into Simulator
        run: |
          xcrun simctl install booted tests/support/app
      - name: Test phoenix_channel_clients
        run: |
          echo "Launching Test Server"
          cd tests/support/test_server && mix phx.server &
          while ! nc -z localhost 9002; do sleep 0.1; done
          echo "Test Server launched"
          xcrun simctl launch --console booted com.rust.tests | tee output
          kill %1
          grep -q "test result: ok." output
